# Project information
site_name: 'Getting Started with Cloud Foundry on .NET'
site_description: 'A tutorial for deploying your first .NET app to Cloud Foundry'

# Repository
repo_name: 'cloudfoundry/docs-dotnet-tutorial'
repo_url: 'https://github.com/cloudfoundry/docs-dotnet-tutorial'

# Configuration
theme:
  name: 'material'
  palette:
    primary: 'blue'
    accent: 'light blue'

# Left navigation
nav:
  - Home: index.md
  - Prerequisites: prerequisites.md
  - Set up environment: setup.md
  - Prepare the app: prepare-app.md
  - Create a manifest: create-manifest.md
  - Configure app logging: configure-app-logs.md
  - Deploy the app: deploy-app.md
  - View app logs: view-app-logs.md
  - Modify web.config: modify-web-config.md
  - Scale the app: scale-app.md
  - Configure health check: config-health-check.md
  - Bind a service: bind-service.md
  - Next steps: next-steps.md

# Extensions
markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
      linenums: true
  - toc:
      permalink: true
plugins:
  - search
  - markdownextradata

# Template variables
extra:
  product_full: Cloud Foundry
  product_short: Cloud Foundry
